es_ES:
    quotes:
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
        -
            author: ''
            quote: ''
