---
quotes:
  - quote: The way to get started is to quit talking and begin doing.
    author: "Walt Disney"
  - quote: The secret to getting ahead is getting started.
    author: "Mark Twain"
  - quote: Great things are done by a series of small things brought together.
    author: "Vincent Van Gogh"
  - quote: To handle yourself, use your head; to handle others, use your heart.
    author: "Eleanor Roosevelt"
  - quote: Don't tell people how to do things, tell them what to do and let them surprise you with their results.
    author: "George Patton"
  - quote: Leadership is the art of getting someone else to do something you want done because he wants to do it.
    author: "Dwight D. Eisenhower"
  - quote: "A leader is a dealer in hope."
    author: "Napoleon"
  - quote: If you want to build a ship, don't drum up the men to gather wood, divide the work, and give orders. Instead, teach them to yearn for the vast and endless sea.
    author: "Antoine de Saint-Exupéry"
  - quote: Whenever you see a successful business, someone once made a courageous decision.
    author: "Peter F. Drucker"
  - quote: Earn your leadership every day.
    author: "Michael Jordan"
  - quote: Our chief want is someone who will inspire us to be what we know we could be.
    author: "Ralph Waldo Emerson"
  - quote: Leadership is a series of behaviors rather than a role for heroes.
    author: "Margaret Wheatley"
  - quote: A leader takes people where they want to go. A great leader takes people where they don't necessarily want to go, but ought to be.
    author: "Rosalynn Carter"
  - quote: Optimism is the faith that leads to achievement.
    author: "Helen Keller"
  - quote: Knowing what must be done does away with fear.
    author: "Rosa Parks"
  - quote: You may not control all the events that happen to you, but you can decide not to be reduced by them.
    author: "Maya Angelou"
  - quote: If you want to lift yourself up, lift up someone else.
    author: "Booker T. Washington"
  - quote: All labor that uplifts humanity has dignity and importance and should be undertaken with painstaking excellence.
    author: "Martin Luther King, Jr."
  - quote: There are opportunities even in the most difficult moments.
    author: "Wangarĩ Maathai"
  - quote: Not everything that is faced can be changed, but nothing can be changed until it is faced.
    author: "James Baldwin"
