en:
    quotes:
        -
            author: 'Walt Disney'
            quote: 'The way to get started is to quit talking and begin doing.'
        -
            author: 'Mark Twain'
            quote: 'The secret to getting ahead is getting started.'
        -
            author: 'Vincent Van Gogh'
            quote: 'Great things are done by a series of small things brought together.'
        -
            author: 'Eleanor Roosevelt'
            quote: 'To handle yourself, use your head; to handle others, use your heart.'
        -
            author: 'George Patton'
            quote: 'Don''t tell people how to do things, tell them what to do and let them surprise you with their results.'
        -
            author: 'Dwight D. Eisenhower'
            quote: 'Leadership is the art of getting someone else to do something you want done because he wants to do it.'
        -
            author: Napoleon
            quote: 'A leader is a dealer in hope.'
        -
            author: 'Antoine de Saint-Exupéry'
            quote: 'If you want to build a ship, don''t drum up the men to gather wood, divide the work, and give orders. Instead, teach them to yearn for the vast and endless sea.'
        -
            author: 'Peter F. Drucker'
            quote: 'Whenever you see a successful business, someone once made a courageous decision.'
        -
            author: 'Michael Jordan'
            quote: 'Earn your leadership every day.'
        -
            author: 'Ralph Waldo Emerson'
            quote: 'Our chief want is someone who will inspire us to be what we know we could be.'
        -
            author: 'Margaret Wheatley'
            quote: 'Leadership is a series of behaviors rather than a role for heroes.'
        -
            author: 'Rosalynn Carter'
            quote: 'A leader takes people where they want to go. A great leader takes people where they don''t necessarily want to go, but ought to be.'
        -
            author: 'Helen Keller'
            quote: 'Optimism is the faith that leads to achievement.'
        -
            author: 'Rosa Parks'
            quote: 'Knowing what must be done does away with fear.'
        -
            author: 'Maya Angelou'
            quote: 'You may not control all the events that happen to you, but you can decide not to be reduced by them.'
        -
            author: 'Booker T. Washington'
            quote: 'If you want to lift yourself up, lift up someone else.'
        -
            author: 'Martin Luther King, Jr.'
            quote: 'All labor that uplifts humanity has dignity and importance and should be undertaken with painstaking excellence.'
        -
            author: 'Wangarĩ Maathai'
            quote: 'There are opportunities even in the most difficult moments.'
        -
            author: 'James Baldwin'
            quote: 'Not everything that is faced can be changed, but nothing can be changed until it is faced.'
